# Generated by Django 3.1.7 on 2021-03-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedName', models.CharField(max_length=200, unique=True)),
                ('temperment', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('age', models.CharField(max_length=200)),
                ('breedName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsapp.breed')),
            ],
        ),
    ]
